[build]
  command = "npm install && npm run build"
  publish = "dist/ticketapp/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# CORS Headers for MovieApp
[[headers]]
  for = "/*" # Aplica a todos los archivos servidos por este sitio (incluyendo remoteEntry.js)
  [headers.values]
    Access-Control-Allow-Origin = "https://movie-ticket-host-mfe.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Max-Age = "86400" # Cache preflight requests for 24 hours